export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';




export const NEW_LINKS_PACK = 'NEW_LINKS_PACK';
export const NEW_SEARCH_RESULT = 'NEW_SEARCH_RESULT';



export const NEW_FAVORITE_REQ = 'NEW_FAVORITE_REQ';
export const DELETE_FAVORITE_REQ = 'DELETE_FAVORITE_REQ';
export const NEW_FAVORITE_DOC = 'NEW_FAVORITE_DOC';
export const DELETE_FAVORITE_DOC = 'DELETE_FAVORITE_DOC';



export default {
    AUTH_REQUEST,
    AUTH_ERROR,
    AUTH_SUCCESS,
    REGISTER_REQUEST,
    REGISTER_ERROR,
    REGISTER_SUCCESS,
    USER_REQUEST,
    USER_ERROR,
    USER_SUCCESS,

    NEW_LINKS_PACK,
    NEW_SEARCH_RESULT,

    NEW_FAVORITE_DOC,
    NEW_FAVORITE_REQ,
    DELETE_FAVORITE_DOC,
    DELETE_FAVORITE_REQ
}