export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';




export const NEW_LINKS_PACK = 'NEW_LINKS_PACK';
export const NEW_SEARCH_RESULT = 'NEW_SEARCH_RESULT';



export const NEW_FAVORITE_REQ = 'NEW_FAVORITE_REQ';
export const EDIT_FAVORITE_REQ = 'EDIT_FAVORITE_REQ';
export const DELETE_FAVORITE_REQ = 'DELETE_FAVORITE_REQ';
export const NEW_FAVORITE_DOC = 'NEW_FAVORITE_DOC';
export const EDIT_FAVORITE_DOC = 'EDIT_FAVORITE_DOC';
export const DELETE_FAVORITE_DOC = 'DELETE_FAVORITE_DOC';
export const UPDATE_FROM_STORAGE = "UPDATE_FROM_STORAGE";
export const SET_ON_FAVORITE_UPDATE = "SET_ON_FAVORITE_UPDATE";
export const DELETE_ON_FAVORITE_UPDATE = "DELETE_ON_FAVORITE_UPDATE";
export const UPDATE_UPDATABLE = 'UPDATE_UPDATABLE';
export default {
    AUTH_REQUEST,
    AUTH_ERROR,
    AUTH_SUCCESS,
    AUTH_LOGOUT,
    REGISTER_REQUEST,
    REGISTER_ERROR,
    REGISTER_SUCCESS,
    USER_REQUEST,
    USER_ERROR,
    USER_SUCCESS,
    NEW_LINKS_PACK,
    NEW_SEARCH_RESULT,

    NEW_FAVORITE_DOC,
    NEW_FAVORITE_REQ,
    EDIT_FAVORITE_DOC,
    EDIT_FAVORITE_REQ,
    DELETE_FAVORITE_DOC,
    DELETE_FAVORITE_REQ,
    UPDATE_FROM_STORAGE,
    SET_ON_FAVORITE_UPDATE,
    DELETE_ON_FAVORITE_UPDATE,
    UPDATE_UPDATABLE,
}